# Done to increase the memory available to gradle.
org.gradle.jvmargs=-Xmx2G

# Fabric Properties
	# check these on https://fabricmc.net/develop
	minecraft_version = 26.3
	fabric_loader = 0.19.5
	loom_version = 1.18-SNAPSHOT

# Mod Properties
	mod_version = 1.10.0
	maven_group = ru.tpsd.eatinganimationmod
	archives_base_name = eating-animation

# Dependencies
	fabric_api = 0.161.0+26.3
